# Generated by Django 2.1.5 on 2019-04-17 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bus_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=45)),
                ('bus_no', models.CharField(max_length=45)),
                ('st_1', models.CharField(max_length=45)),
                ('t_1', models.TimeField()),
                ('st_2', models.CharField(blank=True, max_length=45, null=True)),
                ('t_2', models.TimeField(blank=True, null=True)),
                ('st_3', models.CharField(blank=True, max_length=45, null=True)),
                ('t_3', models.TimeField(blank=True, null=True)),
                ('st_4', models.CharField(blank=True, max_length=45, null=True)),
                ('t_4', models.TimeField(blank=True, null=True)),
                ('st_5', models.CharField(blank=True, max_length=45, null=True)),
                ('t_5', models.TimeField(blank=True, null=True)),
                ('st_6', models.CharField(blank=True, max_length=45, null=True)),
                ('t_6', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
